#!/usr/bin/bash
usage() { echo "Usage: $0
  e.g.  Stage1_makeinputs_v2.sh --cosmics MDC2025ac --dem_emin 95 --BB 1BB --tag MDS3c --tmin 350

"
}

# Function: Exit with error.
exit_abnormal() {
  usage
  exit 1
}
COSMICS="MDC2025ac"
NJOBS=50
LIVETIME="" #seconds
DEM_EMIN=95
BB=1BB
TMIN=350
TAG="MDS3c"
STOPS="MDC2025ac"
RELEASE="MDC2025"
VERSION="ac"
GEN="Signal" #cosmic generator name CRY or CORSIKA only Cat = "Signal"
# Loop: Get the next option;
while getopts ":-:" options; do
  case "${options}" in
    -)
      case "${OPTARG}" in
        njobs)
          NJOBS=${!OPTIND} OPTIND=$(( $OPTIND + 1 ))
          ;;
        cosmics)
          COSMICS=${!OPTIND} OPTIND=$(( $OPTIND + 1 ))
          ;;
        livetime)
          LIVETIME=${!OPTIND} OPTIND=$(( $OPTIND + 1 ))
          ;;
        dem_emin)
          DEM_EMIN=${!OPTIND} OPTIND=$(( $OPTIND + 1 ))
          ;;
        BB)
          BB=${!OPTIND} OPTIND=$(( $OPTIND + 1 ))
          ;;
        tmin)
          TMIN=${!OPTIND} OPTIND=$(( $OPTIND + 1 ))
          ;;
        tag)
          TAG=${!OPTIND} OPTIND=$(( $OPTIND + 1 ))
          ;;
        stops)
          STOPS=${!OPTIND} OPTIND=$(( $OPTIND + 1 ))
          ;;
        release)
          RELEASE=${!OPTIND} OPTIND=$(( $OPTIND + 1 ))
          ;;
        version)
          VERSION=${!OPTIND} OPTIND=$(( $OPTIND + 1 ))
          ;;
        gen)
          GEN=${!OPTIND} OPTIND=$(( $OPTIND + 1 ))
          ;;
        *)
          echo "Unknown option " ${OPTARG}
          exit_abnormal
          ;;
        esac;;
    :)                                    # If expected argument omitted:
      echo "Error: -${OPTARG} requires an argument."
      exit_abnormal                       # Exit abnormally.
      ;;
    *)                                    # If unknown (any other) option:
      exit_abnormal                       # Exit abnormally.
      ;;
    esac
done

rm -f ${TAG}.txt
rm -f ${COSMICS}

echo "accessing files, making file lists"
mu2eDatasetFileList "dts.mu2e.Cosmic${GEN}.${COSMICS}.art" | head -${NJOBS} > ${COSMICS}

# Get number of jobs
NUM_JOBS=$(wc -l ${COSMICS} | awk '{print $1}')

echo "calculating livetime"
mu2e -c Offline/Print/fcl/printCosmicLivetime.fcl -S ${COSMICS} | grep 'Livetime:' | awk -F: '{print $NF}' > ${COSMICS}.livetime
LIVETIME=$(awk '{sum += $1} END {print sum}' ${COSMICS}.livetime)

# Run event calculations to get event counts for all processes
# Using --verbose false to suppress debug output in config file
# For beam_info: capture all lines (full POT calculation details)
BEAM_INFO=$(calculateEvents.py --livetime ${LIVETIME} --BB ${BB} --printpot "print" --verbose false 2>/dev/null)
# Extract POT details as individual variables
BEAM_ONSPILL_TIME=$(echo "${BEAM_INFO}" | grep "on_spill_time=" | awk '{print $NF}')
BEAM_LIVETIME=$(echo "${BEAM_INFO}" | grep "livetime=" | awk '{print $NF}')
BEAM_NPOT=$(echo "${BEAM_INFO}" | grep "^NPOT=" | awk '{print $NF}')
BEAM_NMOT=$(echo "${BEAM_INFO}" | grep "^NMOT=" | awk '{print $NF}')
# Extract just the numeric values from event yields (remove labels and spaces)
DIO_EVENTS=$(calculateEvents.py --livetime ${LIVETIME} --prc "DIO" --BB ${BB} --dioemin ${DEM_EMIN} --printpot "no" --verbose false 2>/dev/null | tail -1 | awk '{print $NF}')
IPA_EVENTS=$(calculateEvents.py --livetime ${LIVETIME} --prc "IPAMichel" --BB ${BB} --ipaemin 70 --printpot "no" --verbose false 2>/dev/null | tail -1 | awk '{print $NF}')
RPC_INTERNAL_EVENTS=$(calculateEvents.py --livetime ${LIVETIME} --prc "RPC" --tmin ${TMIN} --internal 1 --rpcemin 50 --BB ${BB} --printpot "no" --verbose false 2>/dev/null | tail -1 | awk '{print $NF}')
RPC_EXTERNAL_EVENTS=$(calculateEvents.py --livetime ${LIVETIME} --prc "RPC" --tmin ${TMIN} --internal 0 --rpcemin 50 --BB ${BB} --printpot "no" --verbose false 2>/dev/null | tail -1 | awk '{print $NF}')
RMC_INTERNAL_EVENTS=$(calculateEvents.py --livetime ${LIVETIME} --prc "RMC" --tmin ${TMIN} --internal 1 --rmcemin 85 --BB ${BB} --printpot "no" --verbose false 2>/dev/null | tail -1 | awk '{print $NF}')
RMC_EXTERNAL_EVENTS=$(calculateEvents.py --livetime ${LIVETIME} --prc "RMC" --tmin ${TMIN} --internal 0 --rmcemin 85 --BB ${BB} --printpot "no" --verbose false 2>/dev/null | tail -1 | awk '{print $NF}')


# Write configuration in shell-sourceable format
{
  echo "# Configuration file for ensemble ${TAG}"
  echo "# Generated by Stage1_makeinputs_v2.sh"
  echo "njobs=\"${NUM_JOBS}\""
  echo "CosmicJob=\"${COSMICS}\""
  echo "CosmicGen=\"${GEN}\""
  echo "primaries=\"${RELEASE}${VERSION}\""
  echo "muon_stops=\"${STOPS}\""
  echo "onspilltime=\"${LIVETIME}\""
  echo "BB=\"${BB}\""
  echo "DEM_emin=\"${DEM_EMIN}\""
  echo "TMIN=\"${TMIN}\""
  echo ""
  echo "# ===== POT Calculation Details ====="
  echo "beam_onspill_time=\"${BEAM_ONSPILL_TIME}\""
  echo "beam_walltime=\"${BEAM_LIVETIME}\""
  echo "beam_npot=\"${BEAM_NPOT}\""
  echo "beam_nmot=\"${BEAM_NMOT}\""
  echo ""
  echo "# ===== Event Yields (counts) ====="
  echo "dio_events=\"${DIO_EVENTS}\""
  echo "ipa_events=\"${IPA_EVENTS}\""
  echo "rpc_internal_events=\"${RPC_INTERNAL_EVENTS}\""
  echo "rpc_external_events=\"${RPC_EXTERNAL_EVENTS}\""
  echo "rmc_internal_events=\"${RMC_INTERNAL_EVENTS}\""
  echo "rmc_external_events=\"${RMC_EXTERNAL_EVENTS}\""
} > ${TAG}.txt

echo "Configuration written to ${TAG}.txt"
